// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxbTRpaQ4cqdF0rIHF5iybxcdJutmfmC4',
    appId: '1:477166782080:web:c24ccefa7af4fd9d414865',
    messagingSenderId: '477166782080',
    projectId: 'homewall-1206d',
    authDomain: 'homewall-1206d.firebaseapp.com',
    storageBucket: 'homewall-1206d.appspot.com',
    measurementId: 'G-87XQRLMT83',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1ZRJ6ce0ADLZCMVgYDSibQzqnUX77JnM',
    appId: '1:477166782080:android:da638fd7e72b16ba414865',
    messagingSenderId: '477166782080',
    projectId: 'homewall-1206d',
    storageBucket: 'homewall-1206d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBn8IjmHITSZ_-RWoqZkJagjU7iVNJfBo8',
    appId: '1:477166782080:ios:ee65b091bed731f2414865',
    messagingSenderId: '477166782080',
    projectId: 'homewall-1206d',
    storageBucket: 'homewall-1206d.appspot.com',
    iosClientId: '477166782080-535k3htjped527l88cifke8gmm9h5lmr.apps.googleusercontent.com',
    iosBundleId: 'com.example.homeWall',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBn8IjmHITSZ_-RWoqZkJagjU7iVNJfBo8',
    appId: '1:477166782080:ios:ee65b091bed731f2414865',
    messagingSenderId: '477166782080',
    projectId: 'homewall-1206d',
    storageBucket: 'homewall-1206d.appspot.com',
    iosClientId: '477166782080-535k3htjped527l88cifke8gmm9h5lmr.apps.googleusercontent.com',
    iosBundleId: 'com.example.homeWall',
  );
}
